name="atcf_hardware_bbc"
configs=["all"]
default_config="all"
base_repos=["grip", "atcf_hardware_std", "atcf_hardware_apb", "atcf_hardware_video", "atcf_hardware_utils"]
workflow="single"
stages=["configure", "build_sim", "build_verilog"]
doc="""
This repository is for building, testing and running the RISC-V implementations in CDL

It requires ATCF_CDL_TOOLS_PATH to point to an ATCF CDL tools grip directory configured with at least CDL.
"""
logging="Yes"

[env]
PATH="@ATCF_CDL_TOOLS_PATH@/cdl/build:@ATCF_CDL_TOOLS_PATH@/tools/bin:@GRIP_ROOT_PATH@/grip:@PATH@"

[config.all]
repos=["atcf_fpga", "atcf_hardware"]

[repo.atcf_hardware_std]
url="https://github.com/atthecodeface/atcf_hardware_std.git"
branch="master"
path="atcf_hardware_std"
workflow="single"

[repo.atcf_hardware_apb]
url="https://github.com/atthecodeface/atcf_hardware_apb.git"
branch="master"
path="atcf_hardware_apb"
workflow="single"

[repo.atcf_hardware_video]
url="https://github.com/atthecodeface/atcf_hardware_video.git"
branch="master"
path="atcf_hardware_video"
workflow="single"

[repo.atcf_hardware_utils]
url="https://github.com/atthecodeface/atcf_hardware_utils.git"
branch="master"
path="atcf_hardware_utils"
workflow="single"

[repo.atcf_hardware]
url="https://github.com/atthecodeface/cdl_hardware.git"
branch="master"
path="atcf_hardware"
workflow="single"
configure={exec="autoconf && ./configure"}
build_sim={exec="make -j8"}
build_verilog={exec="make -j8 verilog"}

[repo.atcf_fpga]
url="https://github.com/atthecodeface/quartus.git"
branch="master"
path="atcf_fpga"
workflow="single"

[repo.grip]
url="https://github.com/atthecodeface/grip.git"
branch="master"
path="grip"
workflow="readonly"

