name="atcf_hardware_riscv"
configs=["all", "sim"]
default_config="all"
base_repos=["atcf_hardware_std", "atcf_hardware_apb", "atcf_hardware_video", "atcf_hardware_utils"]
workflow="single"
stages=["configure", "build_sim", "build_verilog"]
doc="""
This repository is for building, testing and running the RISC-V implementations in CDL

It requires ATCF_CDL_TOOLS_PATH to point to an ATCF CDL tools grip directory configured with at least CDL.
Hence $(ATCF_CDL_TOOLS_PATH)/tools/bin/cdl will be the cdl tool, and $(ATCF_CDL_TOOLS_PATH)/grip/grip will be the grip tool.
"""
logging="Yes"

[env]
REPO_HOST="https://github.com/atthecodeface/"
# The next line forces ATCF_CDL_TOOLS_PATH into the grip shell environment - and it must be supplied for configure
ATCF_CDL_TOOLS_PATH="@ATCF_CDL_TOOLS_PATH@"
# Having PATH here forces path in to the grip shell environment setting, based of the *current* path given it uses @PATH@
PATH="@ATCF_CDL_TOOLS_PATH@/tools/bin:@ATCF_CDL_TOOLS_PATH@/grip:@PATH@"
BUILD_DIR="@GRIP_ROOT_PATH@/build"
CDL_ROOT="@ATCF_CDL_TOOLS_PATH@/tools"
VERILATOR_ROOT="@ATCF_CDL_TOOLS_PATH@/tools"
VERILATOR_SHARE="@ATCF_CDL_TOOLS_PATH@/tools/share/verilator"

[config.sim]
repos=[]

[config.all]
repos=["atcf_fpga"]

[repo.atcf_hardware_std]
url="@REPO_HOST@atcf_hardware_std.git"
branch="master"
path="atcf_hardware_std"
workflow="single"

[repo.atcf_hardware_apb]
url="@REPO_HOST@atcf_hardware_apb.git"
branch="master"
path="atcf_hardware_apb"
workflow="single"

[repo.atcf_hardware_video]
url="@REPO_HOST@atcf_hardware_video.git"
branch="master"
path="atcf_hardware_video"
workflow="single"

[repo.atcf_hardware_utils]
url="@REPO_HOST@atcf_hardware_utils.git"
branch="master"
path="atcf_hardware_utils"
workflow="single"

[repo.atcf_fpga]
url="@REPO_HOST@quartus.git"
branch="master"
path="atcf_fpga"
workflow="single"

