[all.grip]
changeset = "0f089056427c3c356ba5424b37c96795e6c3d319"
branch = "master"

[all.atcf_hardware_std]
changeset = "bcd1b9a0a17f4a5f626055b0dd2041ad23c122d9"
branch = "master"

[all.atcf_hardware_apb]
changeset = "bd63c69cf6a9e3a09fc62a30ae316d5bdc80e4d9"
branch = "master"

[all.atcf_hardware_video]
changeset = "75bfbfe0399aa6c77f6e6b932f30293936073ac9"
branch = "master"

[all.atcf_hardware_utils]
changeset = "15caceafe64e099c0b1538354c858f89b1350b8c"
branch = "master"

[all.atcf_fpga]
changeset = "3e2f563d640e9b5db069cbcddfbdea8cfd0246c7"
branch = "master"

[all.atcf_hardware]
changeset = "7f7e7a5c4b0520a67d4d196f5907316a275a4496"
branch = "master"

[all.atcf_hardware_ethernet]
changeset = "7f732bd0050b9128faedace1d49fd12940b5e53b"
branch = "master"

[all.atcf_hardware_jtag]
changeset = "dd9458fbdf0401b683b63ba1ca30cd6aee943ddb"
branch = "master"

[all.atcf_hardware_riscv]
changeset = "2e09c78c6720f51954b169b99a9cb72e5c8fa3cc"
branch = "master"

[all.atcf_hardware_crypto]
changeset = "6baa8c72a529f4c887d56e285cab6f8ecd67935f"
branch = "master"

[all.atcf_hardware_analyzer]
changeset = "c95a86efce2136c4f701ce413546491abbea604c"
branch = "master"

[all.atcf_hardware_vcu108]
changeset = "0099397ada9c47a288913f58dec9a2f9110bfa0f"
branch = "master"

[all.atcf_hardware_clocking]
changeset = "60572b533e2fe4cd7f8d1b8e7ca0b0813ce04c37"
branch = "master"

[all.atcf_hardware_reve_r]
changeset = "a4158f2ae6cc469418365a0c27f754ca0f31597e"
branch = "master"

[all.atcf_hardware_networking]
changeset = "9f3f00ec8747e37fee0892ed12131e435fb0e802"
branch = "master"

[all.atcf_hardware_i2c]
changeset = "a74f44cdf0d4e4b24348fb6ec2d07b6df0b393ce"
branch = "master"
