[all.grip]
changeset = "0f089056427c3c356ba5424b37c96795e6c3d319"
branch = "master"

[all.atcf_hardware_std]
changeset = "bcd1b9a0a17f4a5f626055b0dd2041ad23c122d9"
branch = "master"

[all.atcf_hardware_apb]
changeset = "12e67f90737ca91f044a3078ff6c21d0f7579b16"
branch = "master"

[all.atcf_hardware_video]
changeset = "b398b75dad07939a4bb44af1bdc95f3c2eb57115"
branch = "master"

[all.atcf_hardware_utils]
changeset = "2647ae2daafce8a8d8f2b4211382072651de0f51"
branch = "master"

[all.atcf_fpga]
changeset = "3e2f563d640e9b5db069cbcddfbdea8cfd0246c7"
branch = "master"

[all.atcf_hardware]
changeset = "7f7e7a5c4b0520a67d4d196f5907316a275a4496"
branch = "master"

[all.atcf_hardware_ethernet]
changeset = "7f732bd0050b9128faedace1d49fd12940b5e53b"
branch = "master"

[all.atcf_hardware_jtag]
changeset = "eb7425349bf75ffb50fc4cb49f05a34cef6c9fee"
branch = "master"

[all.atcf_hardware_riscv]
changeset = "fcc4d2c8777f537bdd4c04dace6f01cfdefb9eab"
branch = "master"

[all.atcf_hardware_crypto]
changeset = "6baa8c72a529f4c887d56e285cab6f8ecd67935f"
branch = "master"

[all.atcf_hardware_analyzer]
changeset = "c95a86efce2136c4f701ce413546491abbea604c"
branch = "master"

[all.atcf_hardware_vcu108]
changeset = "0099397ada9c47a288913f58dec9a2f9110bfa0f"
branch = "master"

[all.atcf_hardware_clocking]
changeset = "e2e07dc7d98d530a3b8554febd9ce33038b66ee3"
branch = "master"

[all.atcf_hardware_reve_r]
changeset = "8aff4d339d6da4999f99e3f6b9b1b3312cb5ce09"
branch = "master"

[all.atcf_hardware_networking]
changeset = "9f3f00ec8747e37fee0892ed12131e435fb0e802"
branch = "master"

[all.atcf_hardware_i2c]
changeset = "04b121df6c896cb2d47d7cf480aa082157cdbc6d"
branch = "master"

[all.atcf_hardware_io]
changeset = "73f66bb4da76c281afb7842689c253ac821719de"
branch = "master"
