[all.grip]
changeset = "0f089056427c3c356ba5424b37c96795e6c3d319"
branch = "master"

[all.atcf_hardware_std]
changeset = "bcd1b9a0a17f4a5f626055b0dd2041ad23c122d9"
branch = "master"

[all.atcf_hardware_apb]
changeset = "d8d036597810196cd6b352de1ca2412ac9fca1fe"
branch = "master"

[all.atcf_hardware_video]
changeset = "75bfbfe0399aa6c77f6e6b932f30293936073ac9"
branch = "master"

[all.atcf_hardware_utils]
changeset = "15caceafe64e099c0b1538354c858f89b1350b8c"
branch = "master"

[all.atcf_fpga]
changeset = "3e2f563d640e9b5db069cbcddfbdea8cfd0246c7"
branch = "master"

[all.atcf_hardware]
changeset = "7f7e7a5c4b0520a67d4d196f5907316a275a4496"
branch = "master"

[all.atcf_hardware_ethernet]
changeset = "7f732bd0050b9128faedace1d49fd12940b5e53b"
branch = "master"

[all.atcf_hardware_jtag]
changeset = "eb7425349bf75ffb50fc4cb49f05a34cef6c9fee"
branch = "master"

[all.atcf_hardware_riscv]
changeset = "6faec11dddc35325c9f1fb972c81ddc2bf10bcb8"
branch = "master"

[all.atcf_hardware_crypto]
changeset = "6baa8c72a529f4c887d56e285cab6f8ecd67935f"
branch = "master"

[all.atcf_hardware_analyzer]
changeset = "c95a86efce2136c4f701ce413546491abbea604c"
branch = "master"

[all.atcf_hardware_vcu108]
changeset = "0099397ada9c47a288913f58dec9a2f9110bfa0f"
branch = "master"

[all.atcf_hardware_clocking]
changeset = "e2e07dc7d98d530a3b8554febd9ce33038b66ee3"
branch = "master"

[all.atcf_hardware_reve_r]
changeset = "a4158f2ae6cc469418365a0c27f754ca0f31597e"
branch = "master"

[all.atcf_hardware_networking]
changeset = "9f3f00ec8747e37fee0892ed12131e435fb0e802"
branch = "master"

[all.atcf_hardware_i2c]
changeset = "04b121df6c896cb2d47d7cf480aa082157cdbc6d"
branch = "master"

[all.atcf_hardware_io]
changeset = "37f179a7e8bcfef467ea9721bdb9b1355ad4d201"
branch = "master"
